### global variables
@baseUrl = {{$dotenv BACKEND_URL}}
@contentType = application/json

@authcookie = better-auth.session_token={{$dotenv REST-CLIENT_BETTER-AUTH_TOKEN}}



### 1. récupération des stats de l'utilisateur pou
### pour affichage dans le dashboard
### ==============================================
# @name getStats
GET {{baseUrl}}/api/dashboard/stats
Content-Type: {{contentType}}
Cookie: {{authcookie}}


###


