### global variables
@baseUrl = {{$dotenv BACKEND_URL}}
@contentType = application/json

@authcookie = better-auth.session_token={{$dotenv REST-CLIENT_BETTER-AUTH_TOKEN}}


# tomate cerise jaune
@plantId = "137af95e-c626-42ee-9d05-7726aecdcd4d"
# graine origin :pépinière de boistfort
@seedId= 855bb381-ec99-4e1e-9d58-6de42cd94d4e

### 1. Lister des graines
### ==============================================
# @name getAllSeeds
GET {{baseUrl}}/api/seeds?page1&limit=60
Content-Type: {{contentType}}
Cookie: {{authcookie}}


###


### get BY id
### ==============================================
# @name getSeesById
GET {{baseUrl}}/api/seeds/{{seedId}}
Content-Type: {{contentType}}
Cookie: {{authcookie}}



###
PATCH {{baseUrl}}/api/seeds/{{seedId}}
Content-Type: {{contentType}}
Cookie: {{authcookie}}

{
   "plantId": {{plantId}}
}












