### Variables de fichier
@baseUrl = {{$dotenv BACKEND_URL}}
@contentType = application/json

@authcookie = better-auth.session_token={{$dotenv REST-CLIENT_BETTER-AUTH_TOKEN}}


### 1. Lister les session
### ==============================================
# @name getAllSowingSession

GET {{baseUrl}}/api/sowing-sessions?page=1
Content-Type: {{contentType}}
Cookie: {{authcookie}}


###


### get BY id
### ==============================================
# @name getAllSowingSession

GET {{baseUrl}}/api/sowing-sessions/7f030c3a-9032-40c6-9b8c-4bd567a30269
Content-Type: {{contentType}}
Cookie: {{authcookie}}


###


### get BY year
### ==============================================
# @name getAllSowingSession

GET {{baseUrl}}/api/sowing-sessions?year=2025
Content-Type: {{contentType}}
Cookie: {{authcookie}}


###


### get BY status
### ==============================================
# @name getAllSowingSession

GET {{baseUrl}}/api/sowing-sessions?status=planned
Content-Type: {{contentType}}
Cookie: {{authcookie}}


###


### Créer une session 
### ==============================================
# @name createSowingSession

POST {{baseUrl}}/api/sowing-sessions
Content-Type: {{contentType}}
Cookie: {{authcookie}}

{
  "name": "Mon calendrier de printemps",
  "year": "2026",
  "startDate": "Thu Feb 20 2026 22:26:54 GMT+0100",
  "status": "cancelled",
  "notes": "un exemple de calendrier"
}


###


### 3. Modifier une session
### ==============================================
# @name updateSowingSesssion

PATCH {{baseUrl}}/api/sowing-sessions/bd89de7f-4bf7-4803-a703-c1cda88fa5c0
Content-Type: {{contentType}}
Cookie: {{authcookie}}

{
   "name": "test modifer avec l'api"
}


###


### 4. Effacer une session
### ==============================================
# @name deleteSowingSession

DELETE {{baseUrl}}/api/sowing-sessions/bd89de7f-4bf7-4803-a703-c1cda88fa5c0
Content-Type: {{contentType}}
Cookie: {{authcookie}}


###