### global variables
@baseUrl = {{$dotenv BACKEND_URL}}
@contentType = application/json

@authcookie = better-auth.session_token={{$dotenv REST-CLIENT_BETTER-AUTH_TOKEN}}

### contextual variables
# 'Mon calendrier de printemps, planned, startdate: 12 février 2026
@sowingSessionId = dd53cf91-1ec4-41aa-a8c6-f27f73779908
# tomate cerise jaune
@plantId = "137af95e-c626-42ee-9d05-7726aecdcd4d"
# graine origin :pépinière de boistfort
@seedId= 855bb381-ec99-4e1e-9d58-6de42cd94d4e


### 1. Lister les entrées
### ==============================================
# @name getAllSowingEntries
GET {{baseUrl}}/api/sowing-sessions/{{sowingSessionId}}/entries
Content-Type: {{contentType}}
Cookie: {{authcookie}}


###


### get BY Date
### ==============================================
# @name getAllSowingEntries
GET {{baseUrl}}/api/sowing-sessions/{{sowingSessionId}}/entries?actualStartDate=01-03-2026
Content-Type: {{contentType}}
Cookie: {{authcookie}}


###


### get BY id
### ==============================================
# @name getSowingEntryById

@entryId = 6bbf99fc-e119-47d1-89da-ec241cecf6f9

GET {{baseUrl}}/api/sowing-sessions/{{sowingSessionId}}/entries/{{entryId}}
Content-Type: {{contentType}}
Cookie: {{authcookie}}


###


### Créer un entrée semis
### ==============================================
# @name createSowingEntry
POST {{baseUrl}}/api/sowing-sessions/{{sowingSessionId}}/entries
Content-Type: {{contentType}}
Cookie: {{authcookie}}

{
  "seedId": "{{seedId}}",
  "plannedStartDate": "28-3-2026",
  "estimatedEndDate": "1-4-2026",
  "actualEndDate": "1-4-2026",
  "quantity": 10,
  "notes": "testing dashboard",
  "status": "planned"
}


###


### 3. Modifier une entrée semis
### ==============================================
# @name updateentrySesssion

@entryId = 6bbf99fc-e119-47d1-89da-ec241cecf6f9

PATCH {{baseUrl}}/api/sowing-sessions/{{sowingSessionId}}/entries/{{entryId}}
Content-Type: {{contentType}}
Cookie: {{authcookie}}

{
   "status": "growing"
}


###


### 4. Effacer une entrée semis
### ==============================================
# @name deleteSowingEntry
DELETE {{baseUrl}}/api/sowing-sessions/{{sowingSessionId}}/entries/{{entryId}}
Content-Type: {{contentType}}
Cookie: {{authcookie}}


###
Variable Resolution ProcessSystem Variable Architecture