/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedPlantsIndexRouteImport } from './routes/_authenticated/plants/index'
import { Route as DemoStartServerFuncsRouteImport } from './routes/demo/start.server-funcs'
import { Route as DemoStartApiRequestRouteImport } from './routes/demo/start.api-request'
import { Route as DemoApiNamesRouteImport } from './routes/demo/api.names'
import { Route as AuthenticatedPlantsNewRouteImport } from './routes/_authenticated/plants/new'
import { Route as DemoStartSsrIndexRouteImport } from './routes/demo/start.ssr.index'
import { Route as AuthenticatedPlantsIdIndexRouteImport } from './routes/_authenticated/plants/$id/index'
import { Route as DemoStartSsrSpaModeRouteImport } from './routes/demo/start.ssr.spa-mode'
import { Route as DemoStartSsrFullSsrRouteImport } from './routes/demo/start.ssr.full-ssr'
import { Route as DemoStartSsrDataOnlyRouteImport } from './routes/demo/start.ssr.data-only'
import { Route as AuthenticatedPlantsIdEditRouteImport } from './routes/_authenticated/plants/$id/edit'
import { Route as AuthenticatedPlantsIdSeedsNewRouteImport } from './routes/_authenticated/plants/$id/seeds/new'
import { Route as AuthenticatedPlantsIdSeedsSeedIdEditRouteImport } from './routes/_authenticated/plants/$id/seeds/$seedId/edit'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlantsIndexRoute =
  AuthenticatedPlantsIndexRouteImport.update({
    id: '/plants/',
    path: '/plants/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: '/demo/start/server-funcs',
  path: '/demo/start/server-funcs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartApiRequestRoute = DemoStartApiRequestRouteImport.update({
  id: '/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiNamesRoute = DemoApiNamesRouteImport.update({
  id: '/demo/api/names',
  path: '/demo/api/names',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPlantsNewRoute = AuthenticatedPlantsNewRouteImport.update({
  id: '/plants/new',
  path: '/plants/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const DemoStartSsrIndexRoute = DemoStartSsrIndexRouteImport.update({
  id: '/demo/start/ssr/',
  path: '/demo/start/ssr/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPlantsIdIndexRoute =
  AuthenticatedPlantsIdIndexRouteImport.update({
    id: '/plants/$id/',
    path: '/plants/$id/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const DemoStartSsrSpaModeRoute = DemoStartSsrSpaModeRouteImport.update({
  id: '/demo/start/ssr/spa-mode',
  path: '/demo/start/ssr/spa-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrFullSsrRoute = DemoStartSsrFullSsrRouteImport.update({
  id: '/demo/start/ssr/full-ssr',
  path: '/demo/start/ssr/full-ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrDataOnlyRoute = DemoStartSsrDataOnlyRouteImport.update({
  id: '/demo/start/ssr/data-only',
  path: '/demo/start/ssr/data-only',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPlantsIdEditRoute =
  AuthenticatedPlantsIdEditRouteImport.update({
    id: '/plants/$id/edit',
    path: '/plants/$id/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlantsIdSeedsNewRoute =
  AuthenticatedPlantsIdSeedsNewRouteImport.update({
    id: '/plants/$id/seeds/new',
    path: '/plants/$id/seeds/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlantsIdSeedsSeedIdEditRoute =
  AuthenticatedPlantsIdSeedsSeedIdEditRouteImport.update({
    id: '/plants/$id/seeds/$seedId/edit',
    path: '/plants/$id/seeds/$seedId/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/plants/new': typeof AuthenticatedPlantsNewRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/plants/': typeof AuthenticatedPlantsIndexRoute
  '/plants/$id/edit': typeof AuthenticatedPlantsIdEditRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/plants/$id/': typeof AuthenticatedPlantsIdIndexRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
  '/plants/$id/seeds/new': typeof AuthenticatedPlantsIdSeedsNewRoute
  '/plants/$id/seeds/$seedId/edit': typeof AuthenticatedPlantsIdSeedsSeedIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/plants/new': typeof AuthenticatedPlantsNewRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/plants': typeof AuthenticatedPlantsIndexRoute
  '/plants/$id/edit': typeof AuthenticatedPlantsIdEditRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/plants/$id': typeof AuthenticatedPlantsIdIndexRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
  '/plants/$id/seeds/new': typeof AuthenticatedPlantsIdSeedsNewRoute
  '/plants/$id/seeds/$seedId/edit': typeof AuthenticatedPlantsIdSeedsSeedIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/plants/new': typeof AuthenticatedPlantsNewRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/_authenticated/plants/': typeof AuthenticatedPlantsIndexRoute
  '/_authenticated/plants/$id/edit': typeof AuthenticatedPlantsIdEditRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/_authenticated/plants/$id/': typeof AuthenticatedPlantsIdIndexRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
  '/_authenticated/plants/$id/seeds/new': typeof AuthenticatedPlantsIdSeedsNewRoute
  '/_authenticated/plants/$id/seeds/$seedId/edit': typeof AuthenticatedPlantsIdSeedsSeedIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/plants/new'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/plants/'
    | '/plants/$id/edit'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/plants/$id/'
    | '/demo/start/ssr/'
    | '/plants/$id/seeds/new'
    | '/plants/$id/seeds/$seedId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/plants/new'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/plants'
    | '/plants/$id/edit'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/plants/$id'
    | '/demo/start/ssr'
    | '/plants/$id/seeds/new'
    | '/plants/$id/seeds/$seedId/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/dashboard'
    | '/_authenticated/plants/new'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/_authenticated/plants/'
    | '/_authenticated/plants/$id/edit'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/_authenticated/plants/$id/'
    | '/demo/start/ssr/'
    | '/_authenticated/plants/$id/seeds/new'
    | '/_authenticated/plants/$id/seeds/$seedId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  DemoApiNamesRoute: typeof DemoApiNamesRoute
  DemoStartApiRequestRoute: typeof DemoStartApiRequestRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
  DemoStartSsrDataOnlyRoute: typeof DemoStartSsrDataOnlyRoute
  DemoStartSsrFullSsrRoute: typeof DemoStartSsrFullSsrRoute
  DemoStartSsrSpaModeRoute: typeof DemoStartSsrSpaModeRoute
  DemoStartSsrIndexRoute: typeof DemoStartSsrIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plants/': {
      id: '/_authenticated/plants/'
      path: '/plants'
      fullPath: '/plants/'
      preLoaderRoute: typeof AuthenticatedPlantsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/api-request': {
      id: '/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof DemoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/names': {
      id: '/demo/api/names'
      path: '/demo/api/names'
      fullPath: '/demo/api/names'
      preLoaderRoute: typeof DemoApiNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/plants/new': {
      id: '/_authenticated/plants/new'
      path: '/plants/new'
      fullPath: '/plants/new'
      preLoaderRoute: typeof AuthenticatedPlantsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/demo/start/ssr/': {
      id: '/demo/start/ssr/'
      path: '/demo/start/ssr'
      fullPath: '/demo/start/ssr/'
      preLoaderRoute: typeof DemoStartSsrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/plants/$id/': {
      id: '/_authenticated/plants/$id/'
      path: '/plants/$id'
      fullPath: '/plants/$id/'
      preLoaderRoute: typeof AuthenticatedPlantsIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/demo/start/ssr/spa-mode': {
      id: '/demo/start/ssr/spa-mode'
      path: '/demo/start/ssr/spa-mode'
      fullPath: '/demo/start/ssr/spa-mode'
      preLoaderRoute: typeof DemoStartSsrSpaModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/full-ssr': {
      id: '/demo/start/ssr/full-ssr'
      path: '/demo/start/ssr/full-ssr'
      fullPath: '/demo/start/ssr/full-ssr'
      preLoaderRoute: typeof DemoStartSsrFullSsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/data-only': {
      id: '/demo/start/ssr/data-only'
      path: '/demo/start/ssr/data-only'
      fullPath: '/demo/start/ssr/data-only'
      preLoaderRoute: typeof DemoStartSsrDataOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/plants/$id/edit': {
      id: '/_authenticated/plants/$id/edit'
      path: '/plants/$id/edit'
      fullPath: '/plants/$id/edit'
      preLoaderRoute: typeof AuthenticatedPlantsIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plants/$id/seeds/new': {
      id: '/_authenticated/plants/$id/seeds/new'
      path: '/plants/$id/seeds/new'
      fullPath: '/plants/$id/seeds/new'
      preLoaderRoute: typeof AuthenticatedPlantsIdSeedsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plants/$id/seeds/$seedId/edit': {
      id: '/_authenticated/plants/$id/seeds/$seedId/edit'
      path: '/plants/$id/seeds/$seedId/edit'
      fullPath: '/plants/$id/seeds/$seedId/edit'
      preLoaderRoute: typeof AuthenticatedPlantsIdSeedsSeedIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedPlantsNewRoute: typeof AuthenticatedPlantsNewRoute
  AuthenticatedPlantsIndexRoute: typeof AuthenticatedPlantsIndexRoute
  AuthenticatedPlantsIdEditRoute: typeof AuthenticatedPlantsIdEditRoute
  AuthenticatedPlantsIdIndexRoute: typeof AuthenticatedPlantsIdIndexRoute
  AuthenticatedPlantsIdSeedsNewRoute: typeof AuthenticatedPlantsIdSeedsNewRoute
  AuthenticatedPlantsIdSeedsSeedIdEditRoute: typeof AuthenticatedPlantsIdSeedsSeedIdEditRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedPlantsNewRoute: AuthenticatedPlantsNewRoute,
  AuthenticatedPlantsIndexRoute: AuthenticatedPlantsIndexRoute,
  AuthenticatedPlantsIdEditRoute: AuthenticatedPlantsIdEditRoute,
  AuthenticatedPlantsIdIndexRoute: AuthenticatedPlantsIdIndexRoute,
  AuthenticatedPlantsIdSeedsNewRoute: AuthenticatedPlantsIdSeedsNewRoute,
  AuthenticatedPlantsIdSeedsSeedIdEditRoute:
    AuthenticatedPlantsIdSeedsSeedIdEditRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  DemoApiNamesRoute: DemoApiNamesRoute,
  DemoStartApiRequestRoute: DemoStartApiRequestRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
  DemoStartSsrDataOnlyRoute: DemoStartSsrDataOnlyRoute,
  DemoStartSsrFullSsrRoute: DemoStartSsrFullSsrRoute,
  DemoStartSsrSpaModeRoute: DemoStartSsrSpaModeRoute,
  DemoStartSsrIndexRoute: DemoStartSsrIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
