/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedSeedsRouteRouteImport } from './routes/_authenticated/seeds/route'
import { Route as AuthenticatedSowingSessionsIndexRouteImport } from './routes/_authenticated/sowing-sessions/index'
import { Route as AuthenticatedSeedsIndexRouteImport } from './routes/_authenticated/seeds/index'
import { Route as AuthenticatedPlantsIndexRouteImport } from './routes/_authenticated/plants/index'
import { Route as AuthenticatedCalendarIndexRouteImport } from './routes/_authenticated/calendar/index'
import { Route as AuthenticatedSowingSessionsNewRouteImport } from './routes/_authenticated/sowing-sessions/new'
import { Route as AuthenticatedSeedsNewRouteImport } from './routes/_authenticated/seeds/new'
import { Route as AuthenticatedPlantsNewRouteImport } from './routes/_authenticated/plants/new'
import { Route as AuthenticatedPlantsIdIndexRouteImport } from './routes/_authenticated/plants/$id.index'
import { Route as AuthenticatedSeedsIdEditRouteImport } from './routes/_authenticated/seeds/$id.edit'
import { Route as AuthenticatedPlantsIdEditRouteImport } from './routes/_authenticated/plants/$id.edit'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSeedsRouteRoute = AuthenticatedSeedsRouteRouteImport.update({
  id: '/seeds',
  path: '/seeds',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSowingSessionsIndexRoute =
  AuthenticatedSowingSessionsIndexRouteImport.update({
    id: '/sowing-sessions/',
    path: '/sowing-sessions/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSeedsIndexRoute = AuthenticatedSeedsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedSeedsRouteRoute,
} as any)
const AuthenticatedPlantsIndexRoute =
  AuthenticatedPlantsIndexRouteImport.update({
    id: '/plants/',
    path: '/plants/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCalendarIndexRoute =
  AuthenticatedCalendarIndexRouteImport.update({
    id: '/calendar/',
    path: '/calendar/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSowingSessionsNewRoute =
  AuthenticatedSowingSessionsNewRouteImport.update({
    id: '/sowing-sessions/new',
    path: '/sowing-sessions/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSeedsNewRoute = AuthenticatedSeedsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedSeedsRouteRoute,
} as any)
const AuthenticatedPlantsNewRoute = AuthenticatedPlantsNewRouteImport.update({
  id: '/plants/new',
  path: '/plants/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlantsIdIndexRoute =
  AuthenticatedPlantsIdIndexRouteImport.update({
    id: '/plants/$id/',
    path: '/plants/$id/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSeedsIdEditRoute =
  AuthenticatedSeedsIdEditRouteImport.update({
    id: '/$id/edit',
    path: '/$id/edit',
    getParentRoute: () => AuthenticatedSeedsRouteRoute,
  } as any)
const AuthenticatedPlantsIdEditRoute =
  AuthenticatedPlantsIdEditRouteImport.update({
    id: '/plants/$id/edit',
    path: '/plants/$id/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/seeds': typeof AuthenticatedSeedsRouteRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/plants/new': typeof AuthenticatedPlantsNewRoute
  '/seeds/new': typeof AuthenticatedSeedsNewRoute
  '/sowing-sessions/new': typeof AuthenticatedSowingSessionsNewRoute
  '/calendar/': typeof AuthenticatedCalendarIndexRoute
  '/plants/': typeof AuthenticatedPlantsIndexRoute
  '/seeds/': typeof AuthenticatedSeedsIndexRoute
  '/sowing-sessions/': typeof AuthenticatedSowingSessionsIndexRoute
  '/plants/$id/edit': typeof AuthenticatedPlantsIdEditRoute
  '/seeds/$id/edit': typeof AuthenticatedSeedsIdEditRoute
  '/plants/$id/': typeof AuthenticatedPlantsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/plants/new': typeof AuthenticatedPlantsNewRoute
  '/seeds/new': typeof AuthenticatedSeedsNewRoute
  '/sowing-sessions/new': typeof AuthenticatedSowingSessionsNewRoute
  '/calendar': typeof AuthenticatedCalendarIndexRoute
  '/plants': typeof AuthenticatedPlantsIndexRoute
  '/seeds': typeof AuthenticatedSeedsIndexRoute
  '/sowing-sessions': typeof AuthenticatedSowingSessionsIndexRoute
  '/plants/$id/edit': typeof AuthenticatedPlantsIdEditRoute
  '/seeds/$id/edit': typeof AuthenticatedSeedsIdEditRoute
  '/plants/$id': typeof AuthenticatedPlantsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/seeds': typeof AuthenticatedSeedsRouteRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/plants/new': typeof AuthenticatedPlantsNewRoute
  '/_authenticated/seeds/new': typeof AuthenticatedSeedsNewRoute
  '/_authenticated/sowing-sessions/new': typeof AuthenticatedSowingSessionsNewRoute
  '/_authenticated/calendar/': typeof AuthenticatedCalendarIndexRoute
  '/_authenticated/plants/': typeof AuthenticatedPlantsIndexRoute
  '/_authenticated/seeds/': typeof AuthenticatedSeedsIndexRoute
  '/_authenticated/sowing-sessions/': typeof AuthenticatedSowingSessionsIndexRoute
  '/_authenticated/plants/$id/edit': typeof AuthenticatedPlantsIdEditRoute
  '/_authenticated/seeds/$id/edit': typeof AuthenticatedSeedsIdEditRoute
  '/_authenticated/plants/$id/': typeof AuthenticatedPlantsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/seeds'
    | '/dashboard'
    | '/plants/new'
    | '/seeds/new'
    | '/sowing-sessions/new'
    | '/calendar/'
    | '/plants/'
    | '/seeds/'
    | '/sowing-sessions/'
    | '/plants/$id/edit'
    | '/seeds/$id/edit'
    | '/plants/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/plants/new'
    | '/seeds/new'
    | '/sowing-sessions/new'
    | '/calendar'
    | '/plants'
    | '/seeds'
    | '/sowing-sessions'
    | '/plants/$id/edit'
    | '/seeds/$id/edit'
    | '/plants/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/seeds'
    | '/_authenticated/dashboard'
    | '/_authenticated/plants/new'
    | '/_authenticated/seeds/new'
    | '/_authenticated/sowing-sessions/new'
    | '/_authenticated/calendar/'
    | '/_authenticated/plants/'
    | '/_authenticated/seeds/'
    | '/_authenticated/sowing-sessions/'
    | '/_authenticated/plants/$id/edit'
    | '/_authenticated/seeds/$id/edit'
    | '/_authenticated/plants/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/seeds': {
      id: '/_authenticated/seeds'
      path: '/seeds'
      fullPath: '/seeds'
      preLoaderRoute: typeof AuthenticatedSeedsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sowing-sessions/': {
      id: '/_authenticated/sowing-sessions/'
      path: '/sowing-sessions'
      fullPath: '/sowing-sessions/'
      preLoaderRoute: typeof AuthenticatedSowingSessionsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/seeds/': {
      id: '/_authenticated/seeds/'
      path: '/'
      fullPath: '/seeds/'
      preLoaderRoute: typeof AuthenticatedSeedsIndexRouteImport
      parentRoute: typeof AuthenticatedSeedsRouteRoute
    }
    '/_authenticated/plants/': {
      id: '/_authenticated/plants/'
      path: '/plants'
      fullPath: '/plants/'
      preLoaderRoute: typeof AuthenticatedPlantsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendar/': {
      id: '/_authenticated/calendar/'
      path: '/calendar'
      fullPath: '/calendar/'
      preLoaderRoute: typeof AuthenticatedCalendarIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sowing-sessions/new': {
      id: '/_authenticated/sowing-sessions/new'
      path: '/sowing-sessions/new'
      fullPath: '/sowing-sessions/new'
      preLoaderRoute: typeof AuthenticatedSowingSessionsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/seeds/new': {
      id: '/_authenticated/seeds/new'
      path: '/new'
      fullPath: '/seeds/new'
      preLoaderRoute: typeof AuthenticatedSeedsNewRouteImport
      parentRoute: typeof AuthenticatedSeedsRouteRoute
    }
    '/_authenticated/plants/new': {
      id: '/_authenticated/plants/new'
      path: '/plants/new'
      fullPath: '/plants/new'
      preLoaderRoute: typeof AuthenticatedPlantsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plants/$id/': {
      id: '/_authenticated/plants/$id/'
      path: '/plants/$id'
      fullPath: '/plants/$id/'
      preLoaderRoute: typeof AuthenticatedPlantsIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/seeds/$id/edit': {
      id: '/_authenticated/seeds/$id/edit'
      path: '/$id/edit'
      fullPath: '/seeds/$id/edit'
      preLoaderRoute: typeof AuthenticatedSeedsIdEditRouteImport
      parentRoute: typeof AuthenticatedSeedsRouteRoute
    }
    '/_authenticated/plants/$id/edit': {
      id: '/_authenticated/plants/$id/edit'
      path: '/plants/$id/edit'
      fullPath: '/plants/$id/edit'
      preLoaderRoute: typeof AuthenticatedPlantsIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedSeedsRouteRouteChildren {
  AuthenticatedSeedsNewRoute: typeof AuthenticatedSeedsNewRoute
  AuthenticatedSeedsIndexRoute: typeof AuthenticatedSeedsIndexRoute
  AuthenticatedSeedsIdEditRoute: typeof AuthenticatedSeedsIdEditRoute
}

const AuthenticatedSeedsRouteRouteChildren: AuthenticatedSeedsRouteRouteChildren =
  {
    AuthenticatedSeedsNewRoute: AuthenticatedSeedsNewRoute,
    AuthenticatedSeedsIndexRoute: AuthenticatedSeedsIndexRoute,
    AuthenticatedSeedsIdEditRoute: AuthenticatedSeedsIdEditRoute,
  }

const AuthenticatedSeedsRouteRouteWithChildren =
  AuthenticatedSeedsRouteRoute._addFileChildren(
    AuthenticatedSeedsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSeedsRouteRoute: typeof AuthenticatedSeedsRouteRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedPlantsNewRoute: typeof AuthenticatedPlantsNewRoute
  AuthenticatedSowingSessionsNewRoute: typeof AuthenticatedSowingSessionsNewRoute
  AuthenticatedCalendarIndexRoute: typeof AuthenticatedCalendarIndexRoute
  AuthenticatedPlantsIndexRoute: typeof AuthenticatedPlantsIndexRoute
  AuthenticatedSowingSessionsIndexRoute: typeof AuthenticatedSowingSessionsIndexRoute
  AuthenticatedPlantsIdEditRoute: typeof AuthenticatedPlantsIdEditRoute
  AuthenticatedPlantsIdIndexRoute: typeof AuthenticatedPlantsIdIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSeedsRouteRoute: AuthenticatedSeedsRouteRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedPlantsNewRoute: AuthenticatedPlantsNewRoute,
  AuthenticatedSowingSessionsNewRoute: AuthenticatedSowingSessionsNewRoute,
  AuthenticatedCalendarIndexRoute: AuthenticatedCalendarIndexRoute,
  AuthenticatedPlantsIndexRoute: AuthenticatedPlantsIndexRoute,
  AuthenticatedSowingSessionsIndexRoute: AuthenticatedSowingSessionsIndexRoute,
  AuthenticatedPlantsIdEditRoute: AuthenticatedPlantsIdEditRoute,
  AuthenticatedPlantsIdIndexRoute: AuthenticatedPlantsIdIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
